//! Property tests for Claude Code's native output contract.
//!
//! Builder composition is intentionally exercised with arbitrary text. These
//! properties document which bytes are opaque protocol text and which fields
//! are placed in structured JSON, including the fixed event discriminator.

use hookkit_claude::protocol::{PostToolUse, PostToolUseOutput, SessionStart, SessionStartOutput};
use hookkit_core::EventSpec;
use proptest::prelude::*;
use serde_json::Value;

proptest! {
    /// Property: the text SessionStart variant is an opaque successful stdout
    /// payload. It is neither JSON-quoted nor newline-normalized.
    #[test]
    fn session_start_text_is_byte_exact(text in any::<String>()) {
        let emission = SessionStart::emit(SessionStartOutput::text_context(text.clone())).unwrap();

        prop_assert_eq!(emission.stdout(), text.as_bytes());
        prop_assert!(emission.stderr().is_empty());
        prop_assert_eq!(emission.exit_code(), 0);
    }

    /// Property: structured SessionStart context always carries Claude's exact
    /// `SessionStart` discriminator while preserving both arbitrary messages.
    #[test]
    fn session_start_structured_context_has_fixed_identity(
        context in any::<String>(),
        system_message in any::<String>(),
    ) {
        let output = SessionStartOutput::with_context_and_system_message(
            context.clone(),
            system_message.clone(),
        );
        let emission = SessionStart::emit(output).unwrap();
        let value: Value = serde_json::from_slice(emission.stdout()).unwrap();

        prop_assert_eq!(value["hookSpecificOutput"]["hookEventName"].as_str(), Some("SessionStart"));
        prop_assert_eq!(value["hookSpecificOutput"]["additionalContext"].as_str(), Some(context.as_str()));
        prop_assert_eq!(value["systemMessage"].as_str(), Some(system_message.as_str()));
    }

    /// Property: PostToolUse builder methods compose without losing fields;
    /// arbitrary JSON tool output remains a JSON value rather than text.
    #[test]
    fn post_tool_use_builders_are_additive(
        context in any::<String>(),
        reason in any::<String>(),
        message in any::<String>(),
        updated in any::<i64>(),
        continue_session in any::<bool>(),
        suppress_output in any::<bool>(),
    ) {
        let output = PostToolUseOutput::with_context(context.clone())
            .with_updated_tool_output(Value::Number(updated.into())).unwrap()
            .with_block(reason.clone()).unwrap()
            .with_continue(continue_session).unwrap()
            .with_suppress_output(suppress_output).unwrap()
            .with_system_message(message.clone()).unwrap();
        let emission = PostToolUse::emit(output).unwrap();
        let value: Value = serde_json::from_slice(emission.stdout()).unwrap();

        prop_assert_eq!(value["decision"].as_str(), Some("block"));
        prop_assert_eq!(value["reason"].as_str(), Some(reason.as_str()));
        prop_assert_eq!(value["continue"].as_bool(), Some(continue_session));
        prop_assert_eq!(value["suppressOutput"].as_bool(), Some(suppress_output));
        prop_assert_eq!(value["systemMessage"].as_str(), Some(message.as_str()));
        prop_assert_eq!(value["hookSpecificOutput"]["hookEventName"].as_str(), Some("PostToolUse"));
        prop_assert_eq!(value["hookSpecificOutput"]["additionalContext"].as_str(), Some(context.as_str()));
        prop_assert_eq!(value["hookSpecificOutput"]["updatedToolOutput"].as_i64(), Some(updated));
    }

    /// Property: protocol stderr is an independent successful channel. Adding
    /// it cannot change the JSON stdout generated by the wrapped output.
    #[test]
    fn post_tool_protocol_stderr_preserves_successful_stdout(
        context in any::<String>(),
        stderr in any::<String>(),
    ) {
        let plain = PostToolUse::emit(PostToolUseOutput::with_context(context.clone())).unwrap();
        let wrapped = PostToolUse::emit(
            PostToolUseOutput::with_context(context)
                .with_protocol_stderr(stderr.clone()).unwrap()
        ).unwrap();

        prop_assert_eq!(wrapped.stdout(), plain.stdout());
        prop_assert_eq!(wrapped.stderr(), stderr.as_bytes());
        prop_assert_eq!(wrapped.exit_code(), 0);
    }
}
